name: Build and deploy Jekyll website with Streamlit app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set environment variables
      run: echo "github.repository_name=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_ENV
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: docker.pkg.github.com/${{ github.repository }}/${{ github.repository_name }}-streamlit:latest
        build-args: |
          HTTP_PROXY=${{ secrets.HTTP_PROXY }}
          HTTPS_PROXY=${{ secrets.HTTPS_PROXY }}
          NO_PROXY=${{ secrets.NO_PROXY }}
    
    - name: Deploy website
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        publish_dir: ./_site
        publish_branch: gh-pages
        cname: ${{ secrets.CNAME }}
